#!/usr/bin/env bash
#
# One-shot orchestrator for the full M_buffer = 22 production rerun.
# Assumes leaf tables in tables/ have already been generated by
# ./precompute_all_M22.sh.
#
# Sequence (~24h total wall):
#   1. precision_step4 (~10h, dominated by N=60 ~4.5h)
#   2. bern_K35        (~2 min)
#   3. noncritical_K35 (~30s)
#   4. bern_nstability (~14h, dominated by 3x N=60 ~4.5h each)
#
# Logs to logs/run_chain_M22.log; production-run logs go under logs/ as usual.

set -euo pipefail
cd "$(dirname "$0")"

LOGF=logs/run_chain_M22.log
: > "$LOGF"

# Sanity: ensure all leaf tables are in place before kicking off production.
echo "[$(date)] verifying leaf tables..." | tee -a "$LOGF"
required=(
    "tables/mu_K20_p0.5_q0.csv"
    "tables/mu_K35_p0.5_q0.csv"
    "tables/mu_K35_p0.10_q0.csv"
    "tables/mu_K35_p0.20_q0.csv"
    "tables/mu_K35_p0.30_q0.csv"
    "tables/mu_K35_p0.40_q0.csv"
)
for q in 0.00 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50 \
         0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 0.95 1.00; do
    required+=("tables/mu_K35_p0.5_q${q}.csv")
done
for t in "${required[@]}"; do
    if [[ ! -f "$t" ]]; then
        echo "[fail] missing $t" | tee -a "$LOGF" >&2
        exit 1
    fi
done
echo "[$(date)] all 27 leaf tables present" | tee -a "$LOGF"

run_tier() {
    local tier="$1"
    echo "[$(date)] === starting tier: $tier ===" | tee -a "$LOGF"
    local t0 t1
    t0=$(date +%s)
    ./run_production.sh "$tier" 2>&1 | tee -a "$LOGF"
    t1=$(date +%s)
    echo "[$(date)] === tier $tier done ($((t1 - t0))s) ===" | tee -a "$LOGF"
}

run_tier precision_step4
run_tier bern_K35
run_tier noncritical_K35
run_tier bern_nstability

echo "[$(date)] all tiers complete" | tee -a "$LOGF"
